### ISSUE TITLE
Investigate possibility of adding middleware to the store

### ISSUE THREAD

**Issue by AriaFallah** [AriaFallah/mobx-store#10]
@hnordt
Right now I don't see the need for middleware, but also because I haven't really used the store a lot yet.

With Redux most middleware was for either debugging actions, or adding async ability to actions. I think perhaps middleware could be useful on the debugging side, but MobX doesn't seem to inherently need a built in way to handle asynchronously modifying the store.

**Comment by hnordt** [comment]
Yeah, I agree.

**Comment by AriaFallah** [comment]
Closing for now, but will reopen when I want to consider this again.
