### ISSUE TITLE
Dispose of observers when store is no longer used.

### ISSUE THREAD

**Issue by AriaFallah** [AriaFallah/mobx-store#24]
Figure out how to get rid of these observers when the store is garbage collected as per https://github.com/mobxjs/mobx/issues/224#issuecomment-215760543

https://github.com/AriaFallah/mobx-store/blob/master/src/index.js#L85

**Comment by mweststrate** [comment]
I don't think you need that in your case as there is no `unstore` mechanism if looked correctly? Otherwise, `observe` returns a function, which, when invoked, disposes the observer.
