### ISSUE TITLE
schedule doesn't fire

### ISSUE THREAD

**Issue by mochacoder** [AriaFallah/mobx-store#36]
I can't get schedule to fire in a basic use of the store. When searching the repository I see it created in index.js at line 78 and set on the db at line 27 but no other references to it in the repository. I'm thinking it's just not wired up to anything.

**Comment by AriaFallah** [comment]
@mochacoder 

Could you post the code you're trying to schedule? There are some quirks with when your tasks run so it'd be helpful to have the code.

**Comment by mochacoder** [comment]
Yeah whenever I run one of the examples from the site it does work so must be something specific in my code. I'll figure it out, thanks for the quick comment and that autorun link does help.

**Comment by AriaFallah** [comment]
@mochacoder 

No worries. Feel free to continue asking questions.
