### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by ifokeev** [AriaFallah/mobx-store#44]
I developed a real-world tiny app that demonstrates use of `React` with `Mobx` and `Mobx-store`:
https://github.com/ifokeev/support-service

It has a single store, prefetch and server-side rendering. I tried to make it clean and correct.
I think it may be useful for beginners. 
If you have the same view, please, add it to your readme. It's non-commerce project, of course, but it may be used as real-world example or lightweight support-service. 

Thank you in advance.

**Comment by mweststrate** [comment]
Nice!

Op di 23 aug. 2016 om 20:05 schreef 1 <notifications@github.com>:

**Comment by mweststrate** [comment]
Do you have it running somewhere? or some screenshots in the Readme? that
would be valuable :)

Op di 23 aug. 2016 om 20:09 schreef Michel Weststrate <mweststrate@gmail.com

**Comment by ifokeev** [comment]
@mweststrate 
I will upload it in 1 hour and place link here and to the readme.

**Comment by AriaFallah** [comment]
@ifokeev 

I'm really happy you're using the library. I'll put it in the README if you want for sure, but I also have to be a party pooper even if it's my own library.

---

You're using only the `.get` and `.set` methods of the store, which means that you can just replace the line where you use `mobx-store`

```js
import mobxstore from 'mobx-store'

const store = mobxstore(initialState);
```

with

```js
import { observable, asMap } from 'mobx'

const store = observable(asMap(initialState));
```

---

I've tried a lot to use this library in my own projects, and truly, there's no reason to use it over a regular mobx map, especially if you already know what mobx is and how to use it.

Only in the following cases would you use it over a mobx-map:

* You don't know what mobx is, but you want an observable store.
* You need undo/redo, which currently behaves weirdly until I sort out #43 and #41 
* You want to use the declarative querying, which honestly I could separate into a separate module.

Your case fits none of these.

---

Lol, but uh great project. I'll still put it in the README if you want after you read this. I've just come to be a bit disappointed in my own library, and figured you should know you can basically drop the dependency.

**Comment by ifokeev** [comment]
@mweststrate 
http://support-service.vanya.cc/dashboard/
Sorry for the delay lol. Was trying to manage docker. 
Also uploaded dumb managing scripts, but I have no idea how to manage docker easy and fast: https://github.com/ifokeev/docker-dumb-starter-kit

@AriaFallah
Thank you for your response. I've never thought about it. I will refactor scripts based on your recommendations. I started use your library because of undo/redo and maybe I will add this feature later. 

Thank you, guys, for your work and fast responses :)

**Comment by AriaFallah** [comment]
#45
