### ISSUE TITLE
Reducing the size of the package by limiting the available lodash methods to a subset.

### ISSUE THREAD

**Issue by hnordt** [AriaFallah/mobx-store#8]
You had an awesome idea. Thank you for opensourcing it!

I would like to suggest to work if a subset of lodash methods, requiring the entire lodash library may me cumbersome for some projects.

**Comment by AriaFallah** [comment]
@hnordt 

Yeah I wanted to get it working before I started looking at perf and how to fix the problem of large package size.

I'm looking into a solution that's not too limiting, but the biggest problem is just the fact that I don't think it should be my decision what lodash methods are exposed.

This looks somewhat promising, and I'll be looking into it more in the future:

https://medium.com/making-internets/why-using-chain-is-a-mistake-9bc1f80d51ba#.eqjvwsovb

**Comment by AriaFallah** [comment]
@hnordt what do you think of this?

The current API depends on chaining and is

```js
store('x').chain().method().method2().value()
```

instead we change the API so the user has to do

```js
import { method, method2 } from 'lodash/fp' 
store('x', method, method2)
```

and they use https://github.com/lodash/babel-plugin-lodash

**Comment by hnordt** [comment]
I liked the idea of lodash fp. 👍

**Comment by hnordt** [comment]
@AriaFallah do you think is ok for small to medium apps using one store instead multiple?

After you published this library I realized I can have only one store, that's actually the whole state:

```js
class State {
  constructor() {
    this.map = map()
    this.get = this.map.get.bind(this.map)
    this.set = this.map.set.bind(this.map)
  }
  merge = (property, value) => {
    return this.map.set(property, {
      ...this.map.get(property),
      ...value
    })
  }
}

const state = new State()

state.set('color', 'red')
state.set('person', { hnordt: { age: 26 } })
state.merge('person', { AriaFallah: { age: 'unknown'  } })
```

**Comment by AriaFallah** [comment]
@hnordt 

I honestly can't think of many scenarios when you would need multiple instances of `mobx-store`

You can just use different keys for your different data sources like

```js
const store = mobxstore()

store('people').doStuff()
store('colors').doStuff()
store('other').doStuff
```

Also I would recommend not using `mobx-store` yet as the API is about to change if I can fix this issue.

**Comment by hnordt** [comment]
Nice, so mobx store is my app state machine :)

It's like Redux, but with mobx store instead reducing/transforming state manually, it's automatically handled by MobX.

**Comment by hnordt** [comment]
Redux:

Create Store => Create Action => Dispatch Action => Reduce/Transform State => Read State

MobX/MobX Store => Create Store => Creation Action => Dispatch Action => Read State

**Comment by AriaFallah** [comment]
@hnordt haha yeah that was the idea behind this. I'm sure there's more stuff to add to this store to make it a lot better that I'm currently not thinking of as well.

**Comment by hnordt** [comment]
@AriaFallah 

What about supporting middleware like Redux does? Something like:

```
class State {
  constructor(middleware = f => f) {
    this.map = map()
    this.middleware = middleware
  }
  get = key => {
    return this.middleware('get', { key }, this.map.get(key))
  }
  set = (key, value) => {
    return this.middleware('set', { key, value }, this.map.set(key, value))
  }
  merge = (key, value) => {
    return this.set(key, {
      ...this.get(key),
      ...value
    })
  }
}

const middleware = (action, params, nextValue) => {
  if (action === 'get' && typeof nextValue === 'string') {
    return `Next value: ${nextValue}`
  }
  return nextValue
}

const state = new State(middleware)
```

**Comment by AriaFallah** [comment]
Opened #10 for continuing the discussion for middleware there.

**Comment by AriaFallah** [comment]
#11 Fixes this
